loki:
  isDefault: true
  persistence:
    enabled: false
  config:
    table_manager:
      retention_deletes_enabled: true
      retention_period: 168h   # 7 days
promtail:
  enabled: true
  config:
    clients:
      - url: http://loki.logging.svc.cluster.local:3100/loki/api/v1/push
grafana:
  enabled: false
prometheus:
  enabled: false

