apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platformsean-tech
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/platformsean-tech/homelab-aiops-infra.git'
    path: argocd/apps
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

