apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab-aiops
  namespace: argocd
spec:
  project: homelab
  source:
    repoURL: https://github.com/platformsean-tech/homelab-aiops-infra.git
    targetRevision: main
    path: argocd/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

