apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storage
  namespace: argocd
spec:
  project: homelab
  source:
    repoURL: https://github.com/platformsean-tech/homelab-aiops-infra.git
    targetRevision: main
    path: storage
  destination:
    server: https://kubernetes.default.svc
    namespace: storage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

